//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinMPm.Resources.Strings
{
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources
    {
        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ThinMPm.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string Album
        {
            get
            {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }

        public static string Albums
        {
            get
            {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }

        public static string Artist
        {
            get
            {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }

        public static string Artists
        {
            get
            {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }

        public static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        public static string Done
        {
            get
            {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }

        public static string Edit
        {
            get
            {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        public static string FavoriteAdd
        {
            get
            {
                return ResourceManager.GetString("FavoriteAdd", resourceCulture);
            }
        }

        public static string FavoriteArtists
        {
            get
            {
                return ResourceManager.GetString("FavoriteArtists", resourceCulture);
            }
        }

        public static string FavoriteRemove
        {
            get
            {
                return ResourceManager.GetString("FavoriteRemove", resourceCulture);
            }
        }

        public static string FavoriteSongs
        {
            get
            {
                return ResourceManager.GetString("FavoriteSongs", resourceCulture);
            }
        }

        public static string Library
        {
            get
            {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }

        public static string OpenAppSettings
        {
            get
            {
                return ResourceManager.GetString("OpenAppSettings", resourceCulture);
            }
        }

        public static string PermissionDenied
        {
            get
            {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }

        public static string Playlist
        {
            get
            {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }

        public static string PlaylistAdd
        {
            get
            {
                return ResourceManager.GetString("PlaylistAdd", resourceCulture);
            }
        }

        public static string PlaylistCreate
        {
            get
            {
                return ResourceManager.GetString("PlaylistCreate", resourceCulture);
            }
        }

        public static string PlaylistEnter
        {
            get
            {
                return ResourceManager.GetString("PlaylistEnter", resourceCulture);
            }
        }

        public static string PlaylistName
        {
            get
            {
                return ResourceManager.GetString("PlaylistName", resourceCulture);
            }
        }

        public static string PlaylistRemove
        {
            get
            {
                return ResourceManager.GetString("PlaylistRemove", resourceCulture);
            }
        }

        public static string PlaylistRemoveConfirm
        {
            get
            {
                return ResourceManager.GetString("PlaylistRemoveConfirm", resourceCulture);
            }
        }

        public static string PlaylistExistConfirm
        {
            get
            {
                return ResourceManager.GetString("PlaylistExistConfirm", resourceCulture);
            }
        }

        public static string Playlists
        {
            get
            {
                return ResourceManager.GetString("Playlists", resourceCulture);
            }
        }

        public static string RecentlyAdded
        {
            get
            {
                return ResourceManager.GetString("RecentlyAdded", resourceCulture);
            }
        }

        public static string Shortcut
        {
            get
            {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }

        public static string ShortcutAdd
        {
            get
            {
                return ResourceManager.GetString("ShortcutAdd", resourceCulture);
            }
        }

        public static string ShortcutRemove
        {
            get
            {
                return ResourceManager.GetString("ShortcutRemove", resourceCulture);
            }
        }

        public static string Songs
        {
            get
            {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }

        public static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
    }
}
